#!/bin/ksh

# Script to break the VASP DOSCAR file into segments for each atomic site.

# Executables reside here
EXE=$0
BIN=${EXE%/*}

if [ $# -ne 0 ]; then
	echo "Usage: split_dos"
	exit 2
fi

# Script to split the DOSCAR file into the atomic projections labeled by atom number
dosfile=DOSCAR
outfile=OUTCAR
infile=INCAR

# Token for splitting the files
token=$(sed -n '6 p' $dosfile | awk '{print $1}')

# Number of points
nl=$(sed -n '6 p' $dosfile | awk '{print $3}')

# Number of atoms
natom=$(sed -n '1 p' $dosfile | awk '{print $1}')
echo "Number of atoms (natom): $natom"

# Get the Fermi level if the OUTCAR file is present, else set it to zero
if [ -a $outfile ]; then
    echo "The $outfile exists, we use it to get the Fermi level,"
    echo "the RWIGS tag and the number of spins."
    efermi=$(grep "E-fermi" $outfile | tail -1 | awk '{print $3}')
    echo "Fermi level: $efermi"
    nspin=$(grep "ISPIN" $outfile | tail -1 | awk '{print $3}')
    if [ $nspin -eq 2 ]; then
	echo "Spin polarized calculation"
    else
	echo "Unpolarized calculation"
    fi

    # Check LORBIT setting
    lorbit=$(grep "LORBIT" $outfile | tail -1 | awk '{print $3}')
    if [ $lorbit -eq 10 ]; then
        echo "LORBIT = 10"
	form=1
    elif [ $lorbit -eq 11 ];then
        echo "LORBIT = 11"
	form=2
    elif [ $lorbit -eq 12 ];then
        echo "LORBIT = 12"
	form=3
    else
        rwigs=$(grep "RWIGS" $outfile | tail -1 | awk '{print $3}' | sed 's/\.//g')
	if [ $rwigs -eq -100 ]; then
	    echo "RWIGS token not set"
	    form=0
	else
	    echo "RWIGS token set"
	    form=1
	fi
    fi
else
    echo "The $outfile does not exist, we set the Fermi level to 0"
    echo "assume an unpolarized calculation, and RWIGS not set"
    form=0
    nspin=1
    efermi=0.0
fi

# Get the atomic coordinates (Skipping vp since it's not available)
# Assuming tmp.dat2 is correctly formatted and contains atomic coordinates.

# Total DOS is first (DOS0)
i=0

start=7
end=$((start+nl-1))
echo $start $end
rm -f DOS0

# Process DOS0 for the total DOS
if [ $nspin -eq 2 ]; then
    sed -n ''$start','$end' p' $dosfile | awk '{printf "%12.8f %12.8f %12.8f %12.8f %12.8f \n", $1+(-1)*'$efermi', $2, -1*$3, $4, -1*$5 }' >> DOS0
else
    sed -n ''$start','$end' p' $dosfile | awk '{printf "%12.8f %12.8f %12.8f \n", $1+(-1)*'$efermi', $2, $3 }' >> DOS0
fi

# Process DOS for each atom
i=1  # Start from 1 since 0 is for total DOS

while [ $i -le $natom ]; do
    echo "Processing atom $i: start=$start, end=$end"

    if [ $i -ge 1 ]; then
        sed -n ''$i' p' tmp.dat2 >| DOS$i
    fi

    if [ $i -ge 1 ]; then
        # Atomic projected DOS
        if [ $nspin -eq 2 ]; then
            sed -n ''$start','$end' p' $dosfile | awk '{printf "%12.8f %12.8f %12.8f %12.8f %12.8f %12.8f %12.8f \n", $1+(-1)*'$efermi', $2, -1*$3, $4, -1*$5, $6, -1*$7}' >> DOS$i
        else
            sed -n ''$start','$end' p' $dosfile | awk '{printf "%12.8f %12.8f %12.8f %12.8f \n", $1+(-1)*'$efermi', $2, $3, $4 }' >> DOS$i
        fi
    fi

    start=$((end+2))
    end=$((start+nl-1))
    i=$((i+1))
done

exit 0

